global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AdminGriffe API
  - job_name: 'admingriffe-api'
    static_configs:
      - targets: ['api:4000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # Kafka JMX Metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  # Node Exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom audit metrics
  - job_name: 'audit-metrics'
    static_configs:
      - targets: ['api:4000']
    metrics_path: '/api/v1/audit/metrics'
    scrape_interval: 30s

  # Sync metrics
  - job_name: 'sync-metrics'
    static_configs:
      - targets: ['api:4000']
    metrics_path: '/api/v1/sync/metrics'
    scrape_interval: 10s