{{- if and .Values.monitoring.alertmanager.enabled .Values.monitoring.alertmanager.ingress.enabled }}
{{- $fullName := include "worker-sync.fullname" . }}
{{- $svcPort := .Values.monitoring.alertmanager.service.port | default 9093 }}
{{- if and .Values.monitoring.alertmanager.ingress.className (not (hasKey .Values.monitoring.alertmanager.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.monitoring.alertmanager.ingress.annotations "kubernetes.io/ingress.class" .Values.monitoring.alertmanager.ingress.className}}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-alertmanager
  labels:
    {{- include "worker-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
  {{- with .Values.monitoring.alertmanager.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.monitoring.alertmanager.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.monitoring.alertmanager.ingress.className }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.ingress.tls }}
  tls:
    {{- range .Values.monitoring.alertmanager.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.monitoring.alertmanager.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-alertmanager
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-alertmanager
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}