{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "worker-sync.fullname" . }}
  labels:
    {{- include "worker-sync.labels" . | nindent 4 }}
rules:
  # Allow reading pods for health checks and metrics
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # Allow reading services for service discovery
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  # Allow reading endpoints for load balancing
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  # Allow reading configmaps for configuration
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Allow reading secrets for credentials
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  # Allow creating events for logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # Allow reading custom metrics for HPA
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  # Allow reading custom metrics for monitoring
  - apiGroups: ["custom.metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "worker-sync.fullname" . }}
  labels:
    {{- include "worker-sync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "worker-sync.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "worker-sync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}