{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker-sync.fullname" . }}-grafana-secret
  labels:
    {{- include "worker-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
data:
  admin-user: {{ .Values.monitoring.grafana.security.adminUser | b64enc | quote }}
  admin-password: {{ .Values.monitoring.grafana.security.adminPassword | b64enc | quote }}
  {{- if .Values.monitoring.grafana.database.enabled }}
  db-user: {{ .Values.monitoring.grafana.database.user | b64enc | quote }}
  db-password: {{ .Values.monitoring.grafana.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.grafana.smtp.enabled }}
  smtp-user: {{ .Values.monitoring.grafana.smtp.user | b64enc | quote }}
  smtp-password: {{ .Values.monitoring.grafana.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.grafana.ldap.enabled }}
  ldap-bind-password: {{ .Values.monitoring.grafana.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.grafana.oauth.enabled }}
  oauth-client-secret: {{ .Values.monitoring.grafana.oauth.clientSecret | b64enc | quote }}
  {{- end }}
  {{- with .Values.monitoring.grafana.extraSecretData }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}