{{- if .Values.monitoring.alertmanager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker-sync.fullname" . }}-alertmanager-secret
  labels:
    {{- include "worker-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
type: Opaque
data:
  {{- if .Values.monitoring.alertmanager.secrets.smtpAuthPassword }}
  smtp-auth-password: {{ .Values.monitoring.alertmanager.secrets.smtpAuthPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.slackApiUrl }}
  slack-api-url: {{ .Values.monitoring.alertmanager.secrets.slackApiUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.pagerdutyRoutingKey }}
  pagerduty-routing-key: {{ .Values.monitoring.alertmanager.secrets.pagerdutyRoutingKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.webhookUrl }}
  webhook-url: {{ .Values.monitoring.alertmanager.secrets.webhookUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.opsgenieApiKey }}
  opsgenie-api-key: {{ .Values.monitoring.alertmanager.secrets.opsgenieApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.victoropsApiKey }}
  victorops-api-key: {{ .Values.monitoring.alertmanager.secrets.victoropsApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.victoropsRoutingKey }}
  victorops-routing-key: {{ .Values.monitoring.alertmanager.secrets.victoropsRoutingKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.telegramBotToken }}
  telegram-bot-token: {{ .Values.monitoring.alertmanager.secrets.telegramBotToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.telegramChatId }}
  telegram-chat-id: {{ .Values.monitoring.alertmanager.secrets.telegramChatId | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.discordWebhookUrl }}
  discord-webhook-url: {{ .Values.monitoring.alertmanager.secrets.discordWebhookUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.alertmanager.secrets.msteamsWebhookUrl }}
  msteams-webhook-url: {{ .Values.monitoring.alertmanager.secrets.msteamsWebhookUrl | b64enc | quote }}
  {{- end }}
  {{- with .Values.monitoring.alertmanager.secrets.custom }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}