apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-system.fullname" . }}-secrets
  labels:
    {{- include "audit-system.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT Configuration
  jwt-secret: {{ .Values.security.jwt.secret | b64enc | quote }}
  jwt-refresh-secret: {{ .Values.security.jwt.refreshSecret | b64enc | quote }}
  
  # Database Connection Strings
  postgresql-url: {{ include "audit-system.postgresql.connectionString" . | b64enc | quote }}
  mysql-url: {{ include "audit-system.mysql.connectionString" . | b64enc | quote }}
  mongodb-url: {{ include "audit-system.mongodb.connectionString" . | b64enc | quote }}
  
  # Database Credentials
  postgresql-username: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.username | b64enc }}{{ else }}{{ .Values.externalDatabase.postgresql.username | b64enc }}{{ end }}
  postgresql-password: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.password | b64enc }}{{ else }}{{ .Values.externalDatabase.postgresql.password | b64enc }}{{ end }}
  
  mysql-username: {{ if .Values.mysql.enabled }}{{ .Values.mysql.auth.username | b64enc }}{{ else }}{{ .Values.externalDatabase.mysql.username | b64enc }}{{ end }}
  mysql-password: {{ if .Values.mysql.enabled }}{{ .Values.mysql.auth.password | b64enc }}{{ else }}{{ .Values.externalDatabase.mysql.password | b64enc }}{{ end }}
  
  mongodb-username: {{ if .Values.mongodb.enabled }}{{ .Values.mongodb.auth.username | b64enc }}{{ else }}{{ .Values.externalDatabase.mongodb.username | b64enc }}{{ end }}
  mongodb-password: {{ if .Values.mongodb.enabled }}{{ .Values.mongodb.auth.password | b64enc }}{{ else }}{{ .Values.externalDatabase.mongodb.password | b64enc }}{{ end }}
  
  # Cache Configuration
  redis-url: {{ include "audit-system.redis.connectionString" . | b64enc | quote }}
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  redis-password: {{ .Values.externalCache.redis.password | b64enc | quote }}
  {{- end }}
  
  # Encryption Keys
  {{- if .Values.security.encryptionAtRest }}
  encryption-key: {{ .Values.security.encryptionKey | b64enc | quote }}
  {{- end }}
  
  # Audit Signature Keys
  {{- if .Values.security.auditSignature.enabled }}
  audit-signature-private-key: {{ .Values.security.auditSignature.privateKey | b64enc | quote }}
  audit-signature-public-key: {{ .Values.security.auditSignature.publicKey | b64enc | quote }}
  {{- end }}
  
  # Kafka SASL Configuration (if enabled)
  {{- if .Values.kafka.enabled }}
  {{- if .Values.kafka.sasl.enabled }}
  kafka-sasl-username: {{ .Values.kafka.sasl.username | b64enc | quote }}
  kafka-sasl-password: {{ .Values.kafka.sasl.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- if .Values.externalMessaging.kafka.sasl.enabled }}
  kafka-sasl-username: {{ .Values.externalMessaging.kafka.sasl.username | b64enc | quote }}
  kafka-sasl-password: {{ .Values.externalMessaging.kafka.sasl.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  # TLS Certificates (if provided)
  {{- if .Values.security.tls.enabled }}
  tls-cert: {{ .Values.security.tls.cert | b64enc | quote }}
  tls-key: {{ .Values.security.tls.key | b64enc | quote }}
  {{- if .Values.security.tls.ca }}
  tls-ca: {{ .Values.security.tls.ca | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  # External Service API Keys
  {{- if .Values.monitoring.tracing.enabled }}
  jaeger-auth-token: {{ .Values.monitoring.tracing.jaeger.authToken | default "" | b64enc | quote }}
  {{- end }}
  
  # Backup Configuration
  {{- if .Values.backup.enabled }}
  backup-access-key: {{ .Values.backup.s3.accessKey | b64enc | quote }}
  backup-secret-key: {{ .Values.backup.s3.secretKey | b64enc | quote }}
  {{- end }}
  
  # Compliance Export Keys
  {{- if .Values.compliance.encryption.enabled }}
  compliance-encryption-key: {{ .Values.compliance.encryption.key | b64enc | quote }}
  {{- end }}
  
  # SMTP Configuration (for alerts)
  {{- if .Values.monitoring.alerts.email.enabled }}
  smtp-username: {{ .Values.monitoring.alerts.email.smtp.username | b64enc | quote }}
  smtp-password: {{ .Values.monitoring.alerts.email.smtp.password | b64enc | quote }}
  {{- end }}
  
  # Webhook Secrets (for external integrations)
  {{- if .Values.integrations.webhooks.enabled }}
  webhook-secret: {{ .Values.integrations.webhooks.secret | b64enc | quote }}
  {{- end }}
  
  # HSM Configuration (if using Hardware Security Module)
  {{- if .Values.security.hsm.enabled }}
  hsm-pin: {{ .Values.security.hsm.pin | b64enc | quote }}
  hsm-slot-id: {{ .Values.security.hsm.slotId | toString | b64enc | quote }}
  {{- end }}
---
{{- if .Values.security.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-system.fullname" . }}-tls
  labels:
    {{- include "audit-system.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.security.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.security.tls.key | b64enc | quote }}
{{- end }}