{{- if .Values.security.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "audit-system.serviceAccountName" . }}
  labels:
    {{- include "audit-system.labels" . | nindent 4 }}
  {{- with .Values.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.security.serviceAccount.automountServiceAccountToken }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "audit-system.fullname" . }}-cluster-role
  labels:
    {{- include "audit-system.labels" . | nindent 4 }}
rules:
  # Metrics and monitoring
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  # Custom metrics for HPA
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["custom.metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "audit-system.fullname" . }}-cluster-role-binding
  labels:
    {{- include "audit-system.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "audit-system.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "audit-system.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "audit-system.fullname" . }}-role
  labels:
    {{- include "audit-system.labels" . | nindent 4 }}
rules:
  # ConfigMaps and Secrets access
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  # Pod management for scaling
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Events for logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # Lease management for leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "audit-system.fullname" . }}-role-binding
  labels:
    {{- include "audit-system.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "audit-system.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "audit-system.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}